
networks:
  smrcontroller-net:
    driver: bridge

services:
  api:
    build: .
    container_name: smr-api
    ports:
      - "8088:8088"
    volumes:
      - /propertiesapp/smr-api/config/config.json:/app/config/config.json:ro
    environment:
      TZ: "America/Sao_Paulo"
    networks:
      - smrcontroller-net

  frontend:
    build:
      context: ../smr-controller
      dockerfile: Dockerfile
    container_name: smr-frontend
    ports:
      - "3030:80"
    networks:
      - smrcontroller-net
    depends_on:
      - api
