volumes:
  mysql-data:

networks:
  app-net:
    driver: bridge

services:
  mysql:
    image: mysql:8.3.0
    environment:
      MYSQL_ROOT_PASSWORD: SMR@9974!*$
      MYSQL_DATABASE: smrdb
      MYSQL_USER: smr-user
      MYSQL_PASSWORD: SMR@9974!
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - app-net
    restart: unless-stopped

  api:
    build: .
    container_name: smr-api
    ports:
      - "8080:8080"
    volumes:
      # alinhe com o WORKDIR do Dockerfile final
      - /propertiesapp/smr-api/config/config.json:/app/config/config.json:ro
    depends_on:
      - mysql
        #condition: service_healthy
    environment:
      # exemplo de DSN usando o servi√ßo mysql na rede
      # SMR_DSN: "smr-user:${MYSQL_PASSWORD}@tcp(mysql:3306)/smrdb?parseTime=true"
      TZ: "America/Sao_Paulo"
    networks:
      - app-net

  frontend:
    image: node:18
    working_dir: /app
    volumes:
      - ./smr-controller:/app
    command: npm start
    ports:
      - "3000:3000"
    networks:
      - app-net
    depends_on:
      - api