volumes:
  mysql-data:

networks:
  app-net:
    driver: bridge

services:
  mysql:
    image: mysql:8.3.0
    environment:
      MYSQL_ROOT_PASSWORD: SMR@9974!*$
      MYSQL_DATABASE: smrdb
      MYSQL_USER: smr-user
      MYSQL_PASSWORD: SMR@9974!
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - app-net
    restart: unless-stopped

  api:
    build: .
    container_name: smr-api
    ports:
      - "8080:8080"
    volumes:
      - /propertiesapp/smr-api/config/config.json:/app/config/config.json:ro
    depends_on:
      - mysql
    environment:
      TZ: "America/Sao_Paulo"
    networks:
      - app-net

  frontend:
    build:
      context: ../smr-controller
      dockerfile: Dockerfile
    container_name: smr-frontend
    ports:
      - "3000:80"
    networks:
      - app-net
    depends_on:
      - api
