volumes:
  mysql-data:

networks:
  app-net:
    driver: bridge

services:
  mysql:
    image: mysql:8.3.0
    environment:
      MYSQL_ROOT_PASSWORD: SMR@9974!*$
      MYSQL_DATABASE: smrdb
      MYSQL_USER: smr-user
      MYSQL_PASSWORD: SMR@9974!
      # MYSQL_AUTHENTICATION_PLUGIN: caching_sha2_password
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - app-net
    #healthcheck:
    #  test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -u smr-user -p SMR@9974! || exit 1"]
    #  interval: 10s
    #  timeout: 5s
    #  retries: 10
    restart: unless-stopped

  api:
    build: .
    container_name: smr-api
    ports:
      - "8088:8088"
    volumes:
      # alinhe com o WORKDIR do Dockerfile final
      - /propertiesapp/smr-api/config/config.json:/app/config/config.json:ro
    depends_on:
      - mysql
        #condition: service_healthy
    environment:
      # exemplo de DSN usando o servi√ßo mysql na rede
      # SMR_DSN: "smr-user:${MYSQL_PASSWORD}@tcp(mysql:3306)/smrdb?parseTime=true"
      TZ: "America/Sao_Paulo"
    networks:
      - app-net
